.TH DPATH 1 "03 Nov 2012" "version 0.0.5b" "User Commands"
.SH NAME
dpath \- The data path helper script

.SH SYNOPSIS
.B dpath
.BI "--create|-c " "[/path/to/files] "
.BI "--source|-s " "gsiftpSourceUrl"
.BI "--destination|-d " "gsiftpDestinationUrl"
.BI "--alias|-a " "alias"
.B [--configfile
.IB configurationFile ]

.B dpath
.BI "--list|-l " "[/path/to/files] " "[--verbose|-v]"
.B [--configfile
.IB configurationFile ]

.B dpath
.BI "--retrieve|-r " "[/path/to/files] " "[--verbose|-v]"
.B [--configfile
.IB configurationFile ]

.SH DESCRIPTION
.B dpath
is a helper script for 
.B gtransfer
to support users in creating data paths, listing available data paths
and retrieve the latest data paths from a preconfigured repository.

.SH MODES

.B dpath
has several modes of operation:

.TP 10
.B CREATE
Creates a data path file and a link to it named after the
.I alias
that is specified by the user.

.TP
.B LIST
Lists all available data path files. Additionally only sources and destinations
of data paths can be listed.

.TP
.B RETRIEVE
Retrieve the latest data paths available. In this mode
.B dpath
updates the local data paths with data available from the preconfigured
repository.

.SH OPTIONS
.TP
The options are as follows:

.TP
.B CREATE Mode:

.TP
.BI "--create|-c " "[/path/to/files] "
Create a new data path either in the user-provided path or - if no
additional path is given - in the default directory for data paths in:

.I $HOME/.gtransfer/dpaths/

.TP
.BI "--source|-s " "gsiftpSourceUrl"
Set the source URL for the data path without any path portion at the
end.

Example:

.I gsiftp://saturn.milkyway.universe:2811

.TP
.BI "--destination|-d " "gsiftpDestinationUrl"
Set the destination URL for the data path without any path portion at the
end.

Example:

.I gsiftp://pluto.milkyway.universe:2811

.TP
.BI "--alias|-a " "alias"
Set the alias for the created data path.
.B dpath
will create a link named "alias" to the data path file which name is the
SHA1 hash of the source destination combination.

.B NOTICE: Naming of the aliases is not restricted, but one's encouraged to use
.B something like the following:

{{site|organization}_{resource|hostName|FQDN}|Local}--to--{site|organization}_{resource|hostName|FQDN}

.TP
.B LIST Mode:

.TP
.BI "--list|-l " "[/path/to/files] "  "[--verbose|-v]"
List all data paths available in the user-provided path or - if no
additional path is given - in the default and system data path directories.

.TP
.BI "--list-sources " "[/path/to/dataPaths]"
List all sources from the data paths in the user provided path or - if no
additional path is given - in the default and system data path directories.
			
.TP
.BI "--list-destinations " "[/path/to/dataPaths]"
List all destinations from the data paths in the user provided path or - if no
additional path is given - in the default and system data path directories.

.TP
.B RETRIEVE Mode:

.TP
.BI "--retrieve|-r " "[/path/to/files] " "[--quiet|-q]"
Retrieve the latest data paths available on the preconfigured repository and
store them in the user-provided path or - if no additional path is given
- in the default directory for data paths. If a "--quiet|-q" is provided, then output is
omitted and success/failure is only reported by the exit value. 

.TP
.B General options:

.TP
.BI "[--configfile " "configurationFile" "]"
Set the name of the configuration file for
.BR "dpath" ". If not set, this defaults to:"

.IR "/etc/gtransfer/dpath.conf" " or"

.IR "<INSTALL_PATH>/etc/dpath.conf" " or"

.IR "/etc/opt/gtransfer/dpath.conf" " or"

.IR "$HOME/.gtransfer/dpath.conf" " in this order."

.TP
.B [--help]
Prints out a help message.

.TP
.B [--version|-V]
Prints out version information.

.SH FILES
.TP 10
.I $HOME/.gtransfer/dpaths/
This dir contains the default data paths usable by
.BR "gtransfer" ". Can be created with " "dpath" "."

.TP
.I /opt/gtransfer/etc/dpaths/
This dir contains the system data paths usable by
.BR "gtransfer" " and is configurable. Can be created with " "dpath" "."

.TP
.I [...]/dpath.conf
The
.B dpath
configuration file.

.SH AUTHOR
Frank Scheiner

.SH "SEE ALSO"
.BR dparam (1),
.BR sha1sum (1),
.BR tgftp (1),
.BR gtransfer (1)

