.TH DPARAM 1 "24 Jan 2013" "version 0.2.0" "User Commands"
.SH NAME
dparam \- The dparam helper script

.SH SYNOPSIS
.B dparam
.BI "--create|-c " "[/path/to/files] " "[--automatic]"
.BI "--source|-s " "gsiftpSourceUrl"
.BI "--destination|-d " "gsiftpDestinationUrl"
.BI "--alias|-a " "alias"
.B [--configfile
.IB configurationFile ]

.B dparam
.BI "--list|-l " "[/path/to/files] " "[--verbose|-v]"
.B [--configfile
.IB configurationFile ]

.B dparam
.BI "--retrieve|-r " "[/path/to/files] " "[--quiet|-q]"
.B [--configfile
.IB configurationFile ]

.SH DESCRIPTION
.B dparam
is a helper script for 
.B gtransfer
to support users in creating dparams, listing available dparams and retrieve the
latest dparams from a preconfigured repository.

.SH MODES

.B dparam
has several modes of operation:

.TP 10
.B CREATE
Creates a dparam file and a link to it named after the
.I alias
that is specified by the user.

.TP
.B LIST
Lists all available dparams files.

.TP
.B RETRIEVE
Retrieve the latest dparams available. In this mode
.B dparam
updates the local dparams with data available from a preconfigured repository.

.SH OPTIONS
.TP
The options are as follows:

.TP
.B CREATE Mode:

.TP
.BI "--create|-c " "[/path/to/files] " "[--automatic]"
Create a new default param either in the user-provided path or - if no
additional path is given - in the user dparams directory:

.I $HOME/.gtransfer/dparams

If 
.B --automatic
is provided,
.B tgftp
auto-tuning will be used to determine the default param.

.TP
.BI "--source|-s " "gsiftpSourceUrl"
Set the source URL for the dparam without any path portion at the end.

Example:

.I gsiftp://saturn.milkyway.universe:2811

.TP
.BI "--destination|-d " "gsiftpDestinationUrl"
Set the destination URL for the dparam without any path portion at the end.

Example:

.I gsiftp://pluto.milkyway.universe:2811

.TP
.BI "--alias|-a " "alias"
Set the alias for the created default param.
.B dparam
will create a link named "alias" to the dparam file which name is the SHA1 hash
of the source destination combination.

.B NOTICE: Naming of the aliases is not restricted, but one's encouraged to use
.B something like the following:

{{site|organization}_{resource|hostName|FQDN}|Local}--to--{site|organization}_{resource|hostName|FQDN}

.TP
.B LIST Mode:

.TP
.BI "--list|-l " "[/path/to/files] "  "[--verbose|-v]"
List all dparams available in the user-provided path or - if no
additional path is given - in the user and system dparams directories.

.TP
.B RETRIEVE Mode:

.TP
.BI "--retrieve|-r " "[/path/to/files] " "[--quiet|-q]"
Retrieve the latest dparams available on a preconfigured repository and
store them in the user-provided path or - if no additional path is given
- in the user dparams directory. If a "--quiet|-q" is provided, then output is
omitted and success/failure is only reported by the exit value. 

.TP
.B General options:

.TP
.BI "[--configfile " "configurationFile" "]"
Set the name of the configuration file for
.BR "dparam" ". If not set, this defaults to:"

.IR "/etc/gtransfer/dparam.conf" " or"

.IR "<GTRANSFER_BASE_PATH>/etc/dparam.conf" " or"

.IR "/etc/opt/gtransfer/dparam.conf" " or"

.IR "$HOME/.gtransfer/dparam.conf" " or"

.IR "$( dirname $BASH_SOURCE )/../etc" " in this order."

.TP
.B [--help]
Prints out a help message.

.TP
.B [--version|-V]
Prints out version information.

.SH FILES
.TP 10
.I [...]/dparam.conf
The
.B dparam
configuration file.

.TP
.I [...]/dparams/
This dir contains the system dparams usable by
.BR "gtransfer" " and is configurable. Can be created with " "dparam" "."

.TP
.I $HOME/.gtransfer/dparams/
This dir contains the user dparams usable by
.BR "gtransfer" ". Can be created with " "dparam" "."


.SH AUTHOR
Frank Scheiner

.SH "SEE ALSO"
.BR dpath (1),
.BR sha1sum (1),
.BR tgftp (1),
.BR gtransfer (1)

