.TH DPATH 1 "24 Jan 2013" "version 0.1.1" "User Commands"
.SH NAME
dpath \- The dpath helper script

.SH SYNOPSIS
.B dpath
.BI "--create|-c " "[/path/to/files] "
.BI "--source|-s " "gsiftpSourceUrl"
.BI "--destination|-d " "gsiftpDestinationUrl"
.BI "--alias|-a " "alias"
.BI "[--dpath-template " "dpathTemplate" "]"
.BI "[--configfile " "configurationFile" "]"

.B dpath
.BI "--batch-create|-b " "[/path/to/files] "
.BI "--hosts|-h " "hostsFile"
.BI "[--dpath-template " "dpathTemplate" "]"
.BI "[--configfile " "configurationFile" "]"

.B dpath
.BI "--list|-l " "[/path/to/files] " "[--verbose|-v]"
.B [--configfile
.IB configurationFile ]

.B dpath
.BI "--retrieve|-r " "[/path/to/files] " "[--verbose|-v]"
.BI "[--configfile " "configurationFile" "]"

.B dpath
.BI "--reindex " "[/path/to/files] " "[--verbose|-v]"
.BI "[--configfile " "configurationFile" "]"

.SH DESCRIPTION
.B dpath
is a helper script for 
.B gtransfer
to support users in creating dpaths, listing available dpaths and retrieve the
latest dpaths from a preconfigured repository.

.SH MODES

.B dpath
has several modes of operation:

.TP 10
.B CREATE
Creates a dpath file and a link to it named after the
.I alias
that is specified by the user.

.TP
.B BATCH CREATE
Creates all possible dpaths between host addresses given in a file.
Corresponding aliases are created automatically.

.TP
.B LIST
Lists all available dpaths. Additionally only sources and destinations of dpaths
can be listed, too.

.TP
.B RETRIEVE
Retrieve the latest dpaths available. In this mode
.B dpath
updates the local dpaths with data available from a preconfigured repository.

.TP
.B REINDEX
Reindex all dpaths. In this mode
.B dpath 
updates the sources and destinations index files.

.SH OPTIONS
.TP
The options are as follows:

.TP
.B CREATE Mode:

.TP
.BI "--create|-c " "[/path/to/files] "
Create a new dpath either in the user-provided path or - if no additional path
is given - in the user dpaths directory in:

.I $HOME/.gtransfer/dpaths

.TP
.BI "--source|-s " "gsiftpSourceUrl"
Set the source URL for the dpath without any path portion at the end.

Example:

.I gsiftp://saturn.milkyway.universe:2811

.TP
.BI "--destination|-d " "gsiftpDestinationUrl"
Set the destination URL for the dpath without any path portion at the end.

Example:

.I gsiftp://pluto.milkyway.universe:2811

.TP
.BI "--alias|-a " "alias"
Set the alias for the created data path.
.B dpath
will create a link named "alias" to the dpath file which name is the SHA1 hash
of the source destination combination.

.B NOTICE: Naming of the aliases is not restricted, but one's encouraged to use
.B something like the following:

{{site|organization}_{resource|hostName|FQDN}|Local}--to--{site|organization}_{resource|hostName|FQDN}

.TP
.BI "[--dpath-template " "dpathTemplate" "]"
When provided, dpath will use the given template for dpath creation. The
following variables are expanded during dpath creation:

.BR "$sourceWithoutPath " "=> gsiftpSourceUrl => the host address of the source site"

.BR "$destinationWithoutPath " "=> gsiftpDestinationUrl => the host address of the destination site"


.TP
.B BATCH CREATE Mode:

.TP
.BI "--batch-create|-b " "[/path/to/files]"
Create dpaths in batch mode either in the user-provided path or - if no
additional path is given - in the user dpaths directory in:

.I $HOME/.gtransfer/dpaths

When used dpath will create dpaths for all possible connections between the
hosts given in the hostsFile and omit connections between the same hosts.
			
.TP
.BI "--hosts|-h " "hostsFile"
Set the file name for the file containing the host addresses for which dpaths
should be created. The format of each line in this file is as follows:

<PROTOCOL>://hostname.domain.tld:<PORT>

Example contents:

gsiftp://gridftp.omicron.mercury:2811
.br
gsiftp://gridftp.gamma.mars:2812
.br
[...]

.TP
.BI "[--dpath-template " "dpathTemplate" "]"
When provided, dpath will use the given template for dpath creation. The
following variables are expanded during dpath creation:

.BR "$sourceWithoutPath " "=> gsiftpSourceUrl => the host address of the source site"

.BR "$destinationWithoutPath " "=> gsiftpDestinationUrl => the host address of the destination site"


.TP
.B LIST Mode:

.TP
.BI "--list|-l " "[/path/to/files] "  "[--verbose|-v]"
List all dpaths available in the user-provided path or - if no additional path
is given - in the user and system dpaths directories.

.TP
.BI "--list-sources " "[/path/to/dataPaths]"
List all sources from the dpaths in the user provided path or - if no additional
path is given - in the user and system dpaths directories.
			
.TP
.BI "--list-destinations " "[/path/to/dataPaths]"
List all destinations from the dpaths in the user provided path or - if no
additional path is given - in the user and system dpaths directories.


.TP
.B RETRIEVE Mode:

.TP
.BI "--retrieve|-r " "[/path/to/files] " "[--quiet|-q]"
Retrieve the latest dpaths available on the preconfigured repository and store
them in the user-provided path or - if no additional path is given - in the user
dpaths directory. If a "--quiet|-q" is provided, then output is omitted and
success/failure is only reported by the exit value. 


.TP
.B REINDEX Mode:

.TP
.BI "--reindex " "[/path/to/files]"
Reindex all dpaths in the user provided path or - if no additional path is
given - in the user dpaths directory.


.TP
.B General options:

.TP
.BI "[--configfile " "configurationFile" "]"
Set the name of the configuration file for
.BR "dpath" ". If not set, this defaults to:"

.IR "/etc/gtransfer/dpath.conf" " or"

.IR "<GTRANSFER_BASE_PATH>/etc/dpath.conf" " or"

.IR "/etc/opt/gtransfer/dpath.conf" " or"

.IR "$HOME/.gtransfer/dpath.conf" " or"

.IR "$( dirname $BASH_SOURCE )/../etc" " in this order."

.TP
.B [--help]
Prints out a help message.

.TP
.B [--version|-V]
Prints out version information.

.SH FILES
.TP 10
.I [...]/dpath.conf
The
.B dpath
configuration file.

.TP
.I [...]/dpaths/
This dir contains the system dpaths usable by
.BR "gtransfer" " and is configurable. Can be created with " "dpath" "."

.TP
.I $HOME/.gtransfer/dpaths/
This dir contains the user dpaths usable by
.BR "gtransfer" ". Can be created with " "dpath" "."

.TP
.I [...]/dpaths/sources.index
These files (there can be a system one and a user one!) contain all source host
addresses available in the respective dpaths directories. 

.TP
.I [...]/dpaths/destinations.index
These files (there can be a system one and a user one!) contain all destination
host addresses available in the respective dpaths directories.

The index files enable for faster lookup when used by gtransfer's bash
completion. Index files are automatically created and extended when creating
dpaths. The format of each line in these files is as follows:

<PROTOCOL>://hostname.domain.tld:<PORT>

.SH AUTHOR
Frank Scheiner

.SH "SEE ALSO"
.BR dparam (1),
.BR sha1sum (1),
.BR tgftp (1),
.BR gtransfer (1)

