.TH "GTOOLS" "1" "Mar 23, 2017" "gtools 0.3.0" "User Commands"
.SH NAME
.PP
\f[B]gtools\f[]
.SH SYNOPSIS
.PP
\f[B]gtools [function [arguments]...]\f[] or
.PP
\f[B]function [arguments]...\f[] if symlinked
.SH DESCRIPTION
.PP
\f[B]gtools\f[] is a multi\-call shell script that combines various
GridFTP functionality (provided by \f[B]uberftp(1c)\f[]) into a single
executable.
Most people will create a link to gtools for each function they wish to
use and gtools will act like whatever is was invoked as.
.SH COMMON OPTIONS
.PP
All \f[B]gtools\f[] functions provide a terse runtime description of
their behavior when invoked without arguments.
.SH FUNCTIONS
.PP
Currently defined functions:
.PP
(g)cat, (g)ls, (g)mkdir, (g)mv, (g)rm
.PP
All functions support host aliases and remote directory browsing via
bash completion.
Function names are without the \f[B]g[...]\f[] prefix when used as
arguments of \f[B]gtools\f[].
When used directly (via symlinks) the \f[B]g[...]\f[] prefix should be
used to differentiate them from the similar OS tools (\f[B]cat(1)\f[],
\f[B]ls(1)\f[], \f[B]mkdir(1)\f[], \f[B]mv(1)\f[] and \f[B]rm(1)\f[]).
.SH FUNCTION DESCRIPTIONS
.SS (g)cat
.PP
\f[B]gcat \f[I]url\f[]\f[]
.PP
Print to stdout the contents of the remote file given in \f[I]url\f[]
(like \f[B]cat [...]\f[]).
.SS (g)ls
.PP
\f[B]gls \f[I]url\f[]\f[]
.PP
List the remote file or the contents of the remote directory given in
\f[I]url\f[].
Output is similar to \f[B]ls \-la [...]\f[].
.SS (g)mkdir
.PP
\f[B]gmkdir \f[I]url\f[]\f[]
.PP
Create the remote directory given in \f[I]url\f[].
Creates non\-existing directories recursively (like \f[B]mkdir \-p
[...]\f[]) but needs one GridFTP operation per directory!
.SS (g)mv
.PP
\f[B]gmv \f[I]url1\f[] \f[I]url2\f[]\f[]
.PP
Move/rename the remote file or directory in \f[I]url1\f[] to the given
path and/or name in \f[I]url2\f[].
Only works when both \f[I]url1\f[] and \f[I]url2\f[] point to the same
remote GridFTP service!
.SS (g)rm
.PP
\f[B]grm \f[I]url\f[]\f[]
.PP
Remove the remote file (like \f[B]rm [...]\f[]) or empty directory (like
\f[B]rmdir [...]\f[]) given in \f[I]url\f[].
.SH SEE ALSO
.PP
\f[B]uberftp(1c)\f[], \f[B]halias(1)\f[], \f[B]cat(1)\f[],
\f[B]ls(1)\f[], \f[B]mkdir(1)\f[], \f[B]rm(1)\f[], \f[B]rmdir(1)\f[]
.SH AUTHORS
Frank Scheiner.
