.TH GTRANSFER 1 "18 Jan 2013" "version 0.1.0" "User Commands"
.SH NAME
gtransfer \- The GridFTP transfer script

.SH SYNOPSIS
.B {gtransfer|gt}
.BI "[--source|-s " "sourceUrl" "]"
.BI "[--destination|-d " "destinationUrl" "]"
.BI "[--transfer-list|-f " "transferList" "]"
.BI "[--auto-optimize|-o " "transferMode" "]"
.BI "[--guc-max-retries " "gucMaxRetries" "]"
.BI "[--gt-max-retries " "gtMaxRetries" "]"
.BI "[--gt-progress-indicator " "indicatorCharacter" "]"
.B [--verbose|-v] 
.BI "[--metric|-m " "dataPathMetric" "]"
.BI "[--logfile|-l " "logfile" "]"
.B [--auto-clean|-a]
.BI "[--configfile " "configurationFile" "]"
.BI "[-- " "gsiftpParameters" "]"

.SH DESCRIPTION
.B gtransfer
is a wrapper script for
.B tgftp
and provides an advanced interface for performing GridFTP transfers.

.B gtransfer
has the following features:

.TP 10
.B Multi-step data transfers
It can transfer files along predefined paths by using transit sites and can
therefore bridge different network domains.

.TP
.B Optimized data transfer performance
It supports usage of pre-optimized data transfer parameters for specific
connections. Therefore this tool is also helpful for single step transfers. In
addition 
.B gtransfer
can also automatically optimize a data transfer depending on the size of the
files.

.TP
.B Data transfer interruption and continuation
It supports interruption and continuation of transfers. You can interrupt a
transfer by hitting Ctrl+C. To continue an interrupted transfer simply issue the
very same command, 
.B gtransfer
will then continue the transfer where it was interrupted. The same procedure
works for a failed transfer.

.TP
.B Data transfer reliability
It supports automatic retries of failed transfer steps. The number of retries is
configurable.

.TP
.B Bash completion
It makes use of bash completion to ease usage. This supports completion of
options and URLs. URL completion also expands (remote) paths. Just hit the TAB
key to see what's possible.

.SH OPTIONS

The options are as follows:
.TP 10
.BI "[--source|-s " "sourceUrl" "]"
Set the source URL for the transfer.

Possible URL examples:

{[gsi]ftp|http}://FQDN[:PORT]/path/to/file

[file://]/path/to/file

"FQDN" is the fully qualified domain name.

.TP
.BI "[--destination|-d " "destinationUrl" "]"
Set the destination URL for the transfer.

Possible URL examples:

[gsi]ftp://FQDN[:PORT]/path/to/file

[file://]/path/to/file

"FQDN" is the fully qualified domain name.

.TP
.BI "[--transfer-list|-f " "transferList" "]"
As alternative to providing source and destination URLs on the command line, one
can also provide a list of source and destination URLs in a transfer list;
gtransfer will then perform a
.IR "list transfer" " instead of an " "URL transfer" " when using source and destination URLs."
The format of each line of the transfer list file is as follows:

"<PROTOCOL>://source.domain.tld:<PORT>/path/to/file" "<PROTOCOL>://destination.domain.tld:<PORT>/path/to/file[/]"

All lines have to use the exact same source and destination host addresses (i.e.
"gsiftp://host.domain.tld:2811")!

.TP
.BI "[--auto-optimize|-o " "transferMode" "]"
This option activates an automatic optimization of transfers depending on the
size of files to be transferred. If less than 100 files are going to be
transferred, gtransfer will fall back to URL or list transfer depending on
command line options. The
.I transferMode
controls how files of different size classes are transferred. Currently
"seq[uential]" (different size classes are transferred sequentially) is possible.
To define different file size classes use the file
.IR "[...]/chunkConfig" "."
See FILES section below for more details.

.TP
.BI "[--guc-max-retries " "gucMaxRetries" "]"
This option sets the maximum number of retries globus-url-copy (guc) will do for
a transfer of a single file. By default this is set to 1, which means that guc
will tolerate at max. one transfer error per file and retry the transfer once.
Alternatively this option can also be set through the environment variable
"GUC_MAX_RETRIES".

.TP
.BI "[--gt-max-retries " "gtMaxRetries" "]"
This option sets the maximum number of retries gt will do for a single transfer
step. By default this is set to 3, which means that gt will try to finish a
single transfer step three times or fail. Alternatively this option can also be
set through the environment variable "GT_MAX_RETRIES".

.TP
.B [--verbose|-v]
Be verbose.

.TP
.BI "[--metric|-m " "dataPathMetric" "]"
Set the metric to select the corresponding path of a data path.

.TP
.BI "[--logfile|-l " "logfile" "]"
Set the name for the logfile,
.B tgftp
will generate for each transfer. If specified with ".log" as extension,
.B gtransfer
will insert a "__step_#" string to the name of the logfile ("#" is the number of
the transfer step performed). If omitted
.B gtransfer
will automatically generate a name for the logfile(s).

.TP
.B [--auto-clean|-a]
Remove logfiles automatically after the transfer completed.

.TP
.BI "[--configfile " "configurationFile" "]"
Set the name of the configuration file for
.BR "gtransfer" ". If not set, this defaults to:"

.IR "/etc/gtransfer/gtransfer.conf" " or"

.IR "<GTRANSFER_BASE_PATH>/etc/gtransfer.conf" " or"

.IR "/etc/opt/gtransfer/gtransfer.conf" " or"

.IR "$HOME/.gtransfer/gtransfer.conf" " in this order."

.TP
.BI "[-- " "gsiftpParameters" "]"
Set the "globus-url-copy" parameters that should
be used for all transfer steps. Notice the space between
"--" and the actual parameters. This overwrites any
available default parameters and is not recommended for
regular usage. There exists one exception for "-len" or
"-partial-length". If one of these is provided, it will
only be added to the default parameters for a connection
or - if no default parameters are available - to the
builtin default parameters.

.B NOTICE:
If specified, this option must be the last one in a
.B gtransfer
command line.

.TP
.B General options:

.TP
.B [--help]
Prints out a help message.

.TP
.B [--version|-V]
Prints out version information.

.SH FILES
.TP 10
.I [...]/gtransfer.conf
The
.B gtransfer
configuration file.

.TP
.I  [...]/chunkConfig
The chunk configuration file. In this file you can define the different file
size classes for the auto-optimization. Practically the file is a table with
three columns: MIN_SIZE_IN_MB, MAX_SIZE_IN_MB and GUC_PARAMETERS separated by
a semicolon.

Each line defines a size class. The value for MIN_SIZE_IN_MB is
.B not
included in the class. The value for MAX_SIZE_IN_MB is included in the class.
Use the keyword "min" in the column MIN_SIZE_IN_MB to default to the size of the
smallest file available in a transfer list. Files of this size will be included
in this class then. Use the keyword "max" in the column MAX_SIZE_IN_MB to
default to the size of the biggest file available in a transfer list.
The third column (GUC_PARAMETERS) defines the transfer parameters to use for the
specific file size class.

Example:

.nf
#  MIN_SIZE_IN_MB;MAX_SIZE_IN_MB;GUC_PARAMETERS
min;50;-cc 16 -tcp-bs 4M -stripe -sbs 4M -cd
50;250;-cc 8 -tcp-bs 8M -stripe -sbs 4M -cd
250;max;-cc 6 -p 4 -tcp-bs 8M -stripe -sbs 8M -g2 -cd
.fi

.TP
.I [...]/dpaths/
This directory contains the system dpaths usable by
.BR "gtransfer" " and is configurable."

.TP
.I [...]/dparams/
This directory contains the system dparams usable by
.BR "gtransfer" " and is configurable."

.TP
.I $HOME/.gtransfer/dpaths/
This directory contains the user dpaths usable by
.BR "gtransfer" ". Can be created with " "dpath" "."
If existing, dpaths in this directory have precedence.

.TP
.I $HOME/.gtransfer/dparams/
This directory contains the user dparams usable by
.BR "gtransfer" ". Can be created with " "dparam" "."
If existing, dparams in this directory have precedence.


.SH AUTHOR
Frank Scheiner

.SH "SEE ALSO"
.BR dpath (1),
.BR dparam (1),
.BR tgftp (1),
.BR uberftp (1C)

